steps:
  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        files:
          - .buildkite/publish.bash
          - assets/bash_aliases
          - assets/build
          - assets/entrypoint.sh
          - assets/install-build-deps
  - label: ":docker: Build Stretch"
    env:
      DIST: stretch
    command: |
      echo "--- Building images"
      make "DIST=$DIST"
      if [[ "$BUILDKITE_BRANCH" == "master" ]]; then
        echo "--- Publishing $DIST images"
        ./.buildkite/publish.bash
      fi
  - label: ":docker: Build Buster"
    env:
      DIST: buster
    command: |
      echo "--- Building images"
      make "DIST=$DIST"
      if [[ "$BUILDKITE_BRANCH" == "master" ]]; then
        echo "--- Publishing $DIST images"
        ./.buildkite/publish.bash
      fi
